apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front
  name: front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - image: praqma/network-multitool:alpine-extra
        imagePullPolicy: IfNotPresent
        name: frontend
        volumeMounts:
        - mountPath: "/static"
          name: my-volume
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: back
  name: back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - image: praqma/network-multitool:alpine-extra
        imagePullPolicy: IfNotPresent
        name: backend
        volumeMounts:
        - mountPath: "/static"
          name: my-volume
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: pvc
