apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Mi
  hostPath:
    path: /data/pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front-back
  name: front-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-back
  template:
    metadata:
      labels:
        app: front-back
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: frontend
        volumeMounts:
        - mountPath: "/static"
          name: my-volume
      - image: praqma/network-multitool:alpine-extra
        imagePullPolicy: IfNotPresent
        name: backend
        env:
        - name: HTTP_PORT
          value: "8080"
        volumeMounts:
        - mountPath: "/static"
          name: my-volume
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: pvc

