apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  serviceName: "db"
  replicas: {{ .Values.db.replicaCount }}
  minReadySeconds: 0
  template:
    metadata:
      labels:
        app: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
        ports:
        - containerPort: {{ .Values.db.port }}
          name: pg-port
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: {{ .Values.db.dbName }}
        volumeMounts:
        - name: pg-volume
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: pg-volume
          persistentVolumeClaim:
            claimName: postgres-pvc

