apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  ports:
  - name: front
    port: {{ .Values.front.servicePort }}
    targetPort: {{ .Values.front.containerPort }}
  selector:
    app: front

