db:
  replicaCount: 1
  image:
    repository: postgres
    tag: "13-alpine"
  port: 5432
  dbName: news
  storageSize: 100Mi

front:
  replicaCount: 1
  image:
    repository: hw131-frontend
    tag: latest
  containerPort: 80
  servicePort: 8000

back:
  replicaCount: 1
  image:
    repository: hw131-backend
    tag: latest
  port: 9000

